[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --import-mode=importlib -p no:randomly
env = PYTEST_RUNNING=1
filterwarnings =
    ignore::DeprecationWarning:chromadb
    ignore:builtin type Swigpy.*:DeprecationWarning
    ignore:builtin type swigvar.*:DeprecationWarning
    ignore:invalid escape sequence.*:DeprecationWarning