[pytest]
env =
    PYTEST_RUNNING=1
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::FutureWarning
addopts = --ignore=tests/test_pipeline.py --ignore=tests/test_bge_m3.py